apiVersion: v1
kind: Service
metadata:
  name: api-pagamentos-service
  namespace: unifiapay
spec:
  type: NodePort
  selector:
    app: api-pagamentos
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30001
